version: "3.3"
services:
  realworld:
    image: mysql:latest
    restart: "no"
    container_name: mysqlX
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - LANG=C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql/db:/var/lib/mysql